// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8pqNVeC0vJ4g5tj-WmU_uB3BuiEjZTw',
    appId: '1:966056585722:web:78c741e1a0bbfb42c65c43',
    messagingSenderId: '966056585722',
    projectId: 'imc-calculate-104eb',
    authDomain: 'imc-calculate-104eb.firebaseapp.com',
    storageBucket: 'imc-calculate-104eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ODdYBscVMIKlk-LyCmijIZDMNXHfPWo',
    appId: '1:966056585722:android:cf6e2b5fba9a2259c65c43',
    messagingSenderId: '966056585722',
    projectId: 'imc-calculate-104eb',
    storageBucket: 'imc-calculate-104eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRmtY4kcQ51glPjvchrDjrSNEssOFGRRk',
    appId: '1:966056585722:ios:98d4ccff404e1bcfc65c43',
    messagingSenderId: '966056585722',
    projectId: 'imc-calculate-104eb',
    storageBucket: 'imc-calculate-104eb.firebasestorage.app',
    iosBundleId: 'com.example.imc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRmtY4kcQ51glPjvchrDjrSNEssOFGRRk',
    appId: '1:966056585722:ios:98d4ccff404e1bcfc65c43',
    messagingSenderId: '966056585722',
    projectId: 'imc-calculate-104eb',
    storageBucket: 'imc-calculate-104eb.firebasestorage.app',
    iosBundleId: 'com.example.imc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC8pqNVeC0vJ4g5tj-WmU_uB3BuiEjZTw',
    appId: '1:966056585722:web:455a212904a84db9c65c43',
    messagingSenderId: '966056585722',
    projectId: 'imc-calculate-104eb',
    authDomain: 'imc-calculate-104eb.firebaseapp.com',
    storageBucket: 'imc-calculate-104eb.firebasestorage.app',
  );
}
